---
kind: pipeline
name: default
type: docker

steps:
  - name: prettier
    image: node
    commands:
      - npm i prettier
      - npx prettier -c ./slides/**/*.html ./index.html
  - name: jekyll
    image: ruby:2.7
    commands:
      - bundle install
      - bundle exec jekyll build
  - name: htmlhint
    image: node
    commands:
      - npm i htmlhint
      - npx htmlhint ./_site/slides/**/*.html ./_site/index.html

trigger:
  branch:
    - main
