---
kind: pipeline
name: default
type: docker

steps:
  - name: jekyll
    image: ruby
    commands:
      - bundle install
      - bundle exec jekyll build
    when:
      branch:
        - master
  - name: htmlhint
    image: node
    commands:
      - npx htmlhint ./_site/slides/**/*.html ./_site/index.html
    when:
      branch:
        - master
