name: format

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "format-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup nodejs
        uses: actions/setup-node@v7
      - run: npm ci
        name: install npm requirements
      - name: check formatting
        run: npx prettier --check .
